name: Continuous Integration Main
on:
  push:
    branches:
      - main
permissions: read-all

jobs:
  saucelabs-integration-tests:
    runs-on: ubuntu-latest
    permissions: read-all
    env:
      BROWSERSTACK_USER: ${{ secrets.BROWSERSTACK_USER }}
      BROWSERSTACK_KEY: ${{ secrets.BROWSERSTACK_KEY }}
    strategy:
      fail-fast: false
      matrix:
        browser: [edge, ie11, safari, safari-10.1]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-
      - run: npm ci
      - run: npm run compile
      # - name: Run integration tests in Browserstack
      #   run: node ./integration-tests/utils/browserstack.runner.js -e ${{ matrix.browser }} -c ./integration-tests/utils/browserstack.conf.js
      #   timeout-minutes: 15
